### ISSUE TITLE
Unhandled Runtime Error

### ISSUE THREAD

**Issue by rixiobarrios** [rixiobarrios/hilton-dev-assessment#1]
When submitting the valid city chosen a runtime error appears from file; city-weather.tsx, line 39;
Typerror: _Cannot read properties of null (Reading 'main')._

**Source:**

components/city-weather.tsx (39:43) @ CityWeather.render
```

  37 |   <h1>{city}</h1>
  38 |   <div>
> 39 |     Temperature: {KtoF(weatherResult.main.temp).toFixed(0)} &#8457;
     |                                     ^
  40 |   </div>
  41 |   <div>Description: {weatherResult.weather[0].description}</div>
  42 | </div>
```

**Console:**

The above error occurred in the <CityWeather> component:

    at CityWeather (webpack-internal:///./components/city-weather.tsx:38:126)

    at div

    at div

    at IndexPage (webpack-internal:///./pages/index.tsx:21:66)

    at App (webpack-internal:///./pages/_app.tsx:21:24)

    at ErrorBoundary (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:26:47)

    at ReactDevOverlay (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:86:23)

    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:155:5)

    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:643:24)

    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:779:25)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.

**Eslint:** 

'KtoF' was used before it was defined. (@typescript-eslint/no-use-before-define)

**Note:** Error under codesanbox.io environment

**Comment by rixiobarrios** [comment]
Removed the function declaration since it was a (method): (CityWeather.KtoF(tempKevlin: number): number

```
  function KtoF(tempKevlin: number) {
    return ((tempKevlin - 273.15) * 9) / 5 + 32;
  }
```
Moved Method inside its class (class CityWeather).

```
  KtoF(tempKevlin: number) {
    return ((tempKevlin - 273.15) * 9) / 5 + 32;
  }
```

**Comment by rixiobarrios** [comment]
I added "this" to unresolved variable and fixed the spelling of Description on line 46.

```
    return (
      <div>
        <h1>{city}</h1>
        <div>
          Temperature: {this.KtoF(weatherResult.main.temp).toFixed(0)} &#8457;
        </div>
        <div>Description: {weatherResult.weather[0].description}</div>
      </div>
    );
  }
}
```
**Note:** ReferenceError fixed, but after submitting the valid city chosen another runtime error appears;
TypeError: Cannot read properties of null (reading main)

```
  45 |   <h1>{city}</h1>
  46 |   <div>
> 47 |     Temperature: {this.KtoF(weatherResult.main.temp).toFixed(0)} &#8457;
     |                                          ^
  48 |   </div>
  49 |   <div>Description: {weatherResult.weather[0].description}</div>
  50 | </div>
```

**Comment by rixiobarrios** [comment]
I implemented a conditional statement to prevent the API from sending null data and crashing the app.
As denoted on this article: https://stackoverflow.com/questions/66242856/how-to-prevent-a-react-app-crashes-when-an-object-is-passed-as-null

```
    return (
      //I implemented a conditional statement to prevent the API from sending null data and crashing the app.
      weatherResult && (
        <div>
          <h1>{city}</h1>
          <div>
            Temperature: {KtoF(weatherResult.main.temp).toFixed(0)} &#8457;
          </div>
          <div>Description: {weatherResult.weather[0].description}</div>
        </div>
      )
    );
  }
}
```
